replicaCount: 1

namespace: email-services

image:
  repository: galfrylich/service-2-worker
  tag: latest
  pullPolicy: IfNotPresent


env:
  AWS_REGION: ca-central-1
  SQS_QUEUE_URL: "https://sqs.ca-central-1.amazonaws.com/371670420772/dev-email-queue"
  S3_BUCKET: "dev-email-payloads-371670420772"
  POLL_INTERVAL: "10"