replicaCount: 1

namespace: email-services

image:
  repository: galfrylich/service-1-api
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  nodePort: 30080

env:
  AWS_REGION: ca-central-1
  SQS_QUEUE_URL: "https://sqs.ca-central-1.amazonaws.com/371670420772/dev-email-queue"
  JWT_SSM_PARAM: "/dev/email-service/jwt-secret"

