apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: service-1
  template:
    metadata:
      labels:
        app: service-1
    spec:
      containers:
        - name: service-1
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: AWS_REGION
              value: {{ .Values.env.AWS_REGION | quote }}
            - name: SQS_QUEUE_URL
              value: {{ .Values.env.SQS_QUEUE_URL | quote }}
            - name: JWT_SSM_PARAM
              value: {{ .Values.env.JWT_SSM_PARAM | quote }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: AWS_SECRET_ACCESS_KEY   