apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  type: {{ .Values.service.type }}
  selector:
    app: service-1
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      nodePort: {{ .Values.service.nodePort }}